/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProductRouteRouteImport } from './routes/productRoute'
import { Route as HomeRouteRouteImport } from './routes/homeRoute'
import { Route as ContactRouteRouteImport } from './routes/contactRoute'
import { Route as CheckoutSuccessRouteRouteImport } from './routes/checkoutSuccessRoute'
import { Route as CheckoutRouteRouteImport } from './routes/checkoutRoute'
import { Route as ProductRouteIdRouteImport } from './routes/productRoute.$id'

const ProductRouteRoute = ProductRouteRouteImport.update({
  id: '/productRoute',
  path: '/productRoute',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRouteRoute = HomeRouteRouteImport.update({
  id: '/homeRoute',
  path: '/homeRoute',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRouteRoute = ContactRouteRouteImport.update({
  id: '/contactRoute',
  path: '/contactRoute',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRouteRoute = CheckoutSuccessRouteRouteImport.update({
  id: '/checkoutSuccessRoute',
  path: '/checkoutSuccessRoute',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRouteRoute = CheckoutRouteRouteImport.update({
  id: '/checkoutRoute',
  path: '/checkoutRoute',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductRouteIdRoute = ProductRouteIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProductRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/checkoutRoute': typeof CheckoutRouteRoute
  '/checkoutSuccessRoute': typeof CheckoutSuccessRouteRoute
  '/contactRoute': typeof ContactRouteRoute
  '/homeRoute': typeof HomeRouteRoute
  '/productRoute': typeof ProductRouteRouteWithChildren
  '/productRoute/$id': typeof ProductRouteIdRoute
}
export interface FileRoutesByTo {
  '/checkoutRoute': typeof CheckoutRouteRoute
  '/checkoutSuccessRoute': typeof CheckoutSuccessRouteRoute
  '/contactRoute': typeof ContactRouteRoute
  '/homeRoute': typeof HomeRouteRoute
  '/productRoute': typeof ProductRouteRouteWithChildren
  '/productRoute/$id': typeof ProductRouteIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/checkoutRoute': typeof CheckoutRouteRoute
  '/checkoutSuccessRoute': typeof CheckoutSuccessRouteRoute
  '/contactRoute': typeof ContactRouteRoute
  '/homeRoute': typeof HomeRouteRoute
  '/productRoute': typeof ProductRouteRouteWithChildren
  '/productRoute/$id': typeof ProductRouteIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/checkoutRoute'
    | '/checkoutSuccessRoute'
    | '/contactRoute'
    | '/homeRoute'
    | '/productRoute'
    | '/productRoute/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/checkoutRoute'
    | '/checkoutSuccessRoute'
    | '/contactRoute'
    | '/homeRoute'
    | '/productRoute'
    | '/productRoute/$id'
  id:
    | '__root__'
    | '/checkoutRoute'
    | '/checkoutSuccessRoute'
    | '/contactRoute'
    | '/homeRoute'
    | '/productRoute'
    | '/productRoute/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  CheckoutRouteRoute: typeof CheckoutRouteRoute
  CheckoutSuccessRouteRoute: typeof CheckoutSuccessRouteRoute
  ContactRouteRoute: typeof ContactRouteRoute
  HomeRouteRoute: typeof HomeRouteRoute
  ProductRouteRoute: typeof ProductRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/productRoute': {
      id: '/productRoute'
      path: '/productRoute'
      fullPath: '/productRoute'
      preLoaderRoute: typeof ProductRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/homeRoute': {
      id: '/homeRoute'
      path: '/homeRoute'
      fullPath: '/homeRoute'
      preLoaderRoute: typeof HomeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contactRoute': {
      id: '/contactRoute'
      path: '/contactRoute'
      fullPath: '/contactRoute'
      preLoaderRoute: typeof ContactRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkoutSuccessRoute': {
      id: '/checkoutSuccessRoute'
      path: '/checkoutSuccessRoute'
      fullPath: '/checkoutSuccessRoute'
      preLoaderRoute: typeof CheckoutSuccessRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkoutRoute': {
      id: '/checkoutRoute'
      path: '/checkoutRoute'
      fullPath: '/checkoutRoute'
      preLoaderRoute: typeof CheckoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/productRoute/$id': {
      id: '/productRoute/$id'
      path: '/$id'
      fullPath: '/productRoute/$id'
      preLoaderRoute: typeof ProductRouteIdRouteImport
      parentRoute: typeof ProductRouteRoute
    }
  }
}

interface ProductRouteRouteChildren {
  ProductRouteIdRoute: typeof ProductRouteIdRoute
}

const ProductRouteRouteChildren: ProductRouteRouteChildren = {
  ProductRouteIdRoute: ProductRouteIdRoute,
}

const ProductRouteRouteWithChildren = ProductRouteRoute._addFileChildren(
  ProductRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  CheckoutRouteRoute: CheckoutRouteRoute,
  CheckoutSuccessRouteRoute: CheckoutSuccessRouteRoute,
  ContactRouteRoute: ContactRouteRoute,
  HomeRouteRoute: HomeRouteRoute,
  ProductRouteRoute: ProductRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
