/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProductRouteRouteImport } from './routes/productRoute'
import { Route as ProductRouteIdRouteImport } from './routes/productRoute.$id'

const ProductRouteRoute = ProductRouteRouteImport.update({
  id: '/productRoute',
  path: '/productRoute',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductRouteIdRoute = ProductRouteIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProductRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/productRoute': typeof ProductRouteRouteWithChildren
  '/productRoute/$id': typeof ProductRouteIdRoute
}
export interface FileRoutesByTo {
  '/productRoute': typeof ProductRouteRouteWithChildren
  '/productRoute/$id': typeof ProductRouteIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/productRoute': typeof ProductRouteRouteWithChildren
  '/productRoute/$id': typeof ProductRouteIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/productRoute' | '/productRoute/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/productRoute' | '/productRoute/$id'
  id: '__root__' | '/productRoute' | '/productRoute/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProductRouteRoute: typeof ProductRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/productRoute': {
      id: '/productRoute'
      path: '/productRoute'
      fullPath: '/productRoute'
      preLoaderRoute: typeof ProductRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/productRoute/$id': {
      id: '/productRoute/$id'
      path: '/$id'
      fullPath: '/productRoute/$id'
      preLoaderRoute: typeof ProductRouteIdRouteImport
      parentRoute: typeof ProductRouteRoute
    }
  }
}

interface ProductRouteRouteChildren {
  ProductRouteIdRoute: typeof ProductRouteIdRoute
}

const ProductRouteRouteChildren: ProductRouteRouteChildren = {
  ProductRouteIdRoute: ProductRouteIdRoute,
}

const ProductRouteRouteWithChildren = ProductRouteRoute._addFileChildren(
  ProductRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProductRouteRoute: ProductRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
